# Generated by Django 2.2.2 on 2019-06-23 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedaa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedaa.Feed'),
            preserve_default=False,
        ),
    ]
